version: "3"
services:
  server:
    build: ./server
    expose: 
        - "8393"
    ports:
      - "8393:8393"
    command: npm start
  client:
    build: ./client
    expose: 
        - "3000"
    ports:
      - "3000:3000"
    links:
        - server
    stdin_open: true
    tty: true
    command: npm start